<a href="https://colab.research.google.com/github/poojakota17/Data-Mining-255/blob/main/FrequentPatternMining.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Objective : Perform frequent pattern mining algortihms : Apriori and Fpgrowth

Dataset : This dataset is a groceries data set bought by customers. 

> Our aim is to find the frequent patterns using a minimum threshold using apriori and fpgrowth.

## Uploading the dataset.

In [1]:
from google.colab import files
uploaded = files.upload()

Saving groceries - groceries.csv to groceries - groceries (2).csv

> Install the necessary libraries for association rules, apriori and fpgrowth.

In [7]:
import pandas as pd
import io
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import association_rules
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import fpgrowth

## Dataset looks like below

In [3]:
df=pd.read_csv(io.StringIO(uploaded['groceries - groceries.csv'].decode('utf-8')))
df

      Item(s)               Item 1               Item 2  ... Item 30 Item 31 Item 32
0           4         citrus fruit  semi-finished bread  ...     NaN     NaN     NaN
1           3       tropical fruit               yogurt  ...     NaN     NaN     NaN
2           1           whole milk                  NaN  ...     NaN     NaN     NaN
3           4            pip fruit               yogurt  ...     NaN     NaN     NaN
4           4     other vegetables           whole milk  ...     NaN     NaN     NaN
...       ...                  ...                  ...  ...     ...     ...     ...
9830       17              sausage              chicken  ...     NaN     NaN     NaN
9831        1    cooking chocolate                  NaN  ...     NaN     NaN     NaN
9832       10              chicken         citrus fruit  ...     NaN     NaN     NaN
9833        4  semi-finished bread        bottled water  ...     NaN     NaN     NaN
9834        5              chicken       tropical fruit  ...     NaN     NaN     NaN

[9835 rows x 33 columns]

> This is how the dataset info looks like. It has 33 columns.

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9835 entries, 0 to 9834
Data columns (total 33 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Item(s)  9835 non-null   int64
 1   Item 1   9835 non-null   object
 2   Item 2   7676 non-null   object
 3   Item 3   6033 non-null   object
 4   Item 4   4734 non-null   object
 5   Item 5   3729 non-null   object
 6   Item 6   2874 non-null   object
 7   Item 7   2229 non-null   object
 8   Item 8   1684 non-null   object
 9   Item 9   1246 non-null   object
 10  Item 10  896 non-null    object
 11  Item 11  650 non-null    object
 12  Item 12  468 non-null    object
 13  Item 13  351 non-null    object
 14  Item 14  273 non-null    object
 15  Item 15  196 non-null    object
 16  Item 16  141 non-null    object
 17  Item 17  95 non-null     object
 18  Item 18  66 non-null     object
 19  Item 19  52 non-null     object
 20  Item 20  38 non-null     object
 21  Item 21  29 non-null     object
 22  Item 22  18 non-null     object
 23  Item 23  14 non-null     object
 24  Item 24  8 non-null      object
 25  Item 25  7 non-null      object
 26  Item 26  7 non-null      object
 27  Item 27  6 non-null      object
 28  Item 28  5 non-null      object
 29  Item 29  4 non-null      object
 30  Item 30  1 non-null      object
 31  Item 31  1 non-null      object
 32  Item 32  1 non-null      object
dtypes: int64(1), object(32)
memory usage: 2.5+ MB

## One hot encoding

> We are dropping the Item(s) column and creating a one hot encoding

In [5]:
basket_sets = pd.get_dummies(df.drop(columns=['Item(s)'],axis=1), prefix="item")
basket_sets = basket_sets.groupby(level=0, axis=1).sum()
basket_sets

      item_Instant food products  item_UHT-milk  ...  item_yogurt  item_zwieback
0                              0              0  ...            0              0
1                              0              0  ...            1              0
2                              0              0  ...            0              0
3                              0              0  ...            1              0
4                              0              0  ...            0              0
...                          ...            ...  ...          ...            ...
9830                           0              0  ...            0              0
9831                           0              0  ...            0              0
9832                           0              0  ...            1              0
9833                           0              0  ...            0              0
9834                           0              0  ...            0              0

[9835 rows x 169 columns]

# Apriori Algorithm

> We are applying the apriori algorithm with min_support as 0.05

> We can see the frequent items with min_support>=0.05 as below. There are 30 itemsets.

In [15]:
frequent_itemsets = apriori(basket_sets, min_support=0.05, use_colnames=True)
frequent_itemsets

     support                                  itemsets
0   0.052466                               (item_beef)
1   0.080529                       (item_bottled beer)
2   0.110524                      (item_bottled water)
3   0.064870                        (item_brown bread)
4   0.055414                             (item_butter)
5   0.077682                        (item_canned beer)
6   0.082766                       (item_citrus fruit)
7   0.058058                             (item_coffee)
8   0.053279                               (item_curd)
9   0.063447                      (item_domestic eggs)
10  0.058973                        (item_frankfurter)
11  0.072293              (item_fruit/vegetable juice)
12  0.058566                          (item_margarine)
13  0.052364                            (item_napkins)
14  0.079817                         (item_newspapers)
15  0.193493                   (item_other vegetables)
16  0.088968                             (item_pastry)
17  0.075648                          (item_pip fruit)
18  0.057651                               (item_pork)
19  0.183935                         (item_rolls/buns)
20  0.108998                    (item_root vegetables)
21  0.093950                            (item_sausage)
22  0.098526                      (item_shopping bags)
23  0.174377                               (item_soda)
24  0.104931                     (item_tropical fruit)
25  0.071683                 (item_whipped/sour cream)
26  0.255516                         (item_whole milk)
27  0.139502                             (item_yogurt)
28  0.074835  (item_other vegetables, item_whole milk)
29  0.056634        (item_whole milk, item_rolls/buns)
30  0.056024            (item_yogurt, item_whole milk)

## Association rules

> Here we are printing the association rules using the lift metric and min_threshold as 1.

In [9]:
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)
rules.head(100)

               antecedents              consequents  ...  leverage  conviction
0  (item_other vegetables)        (item_whole milk)  ...  0.025394    1.214013
1        (item_whole milk)  (item_other vegetables)  ...  0.025394    1.140548
2        (item_whole milk)        (item_rolls/buns)  ...  0.009636    1.048452
3        (item_rolls/buns)        (item_whole milk)  ...  0.009636    1.075696
4            (item_yogurt)        (item_whole milk)  ...  0.020379    1.244132
5        (item_whole milk)            (item_yogurt)  ...  0.020379    1.102157

[6 rows x 9 columns]

## Patterns

38% of the transactions containing vegetables contain whole milk.

29% of transactions containing whole milk have vegetables.

22% of transactions containing whole milk have rolls/buns.

30% of transactions containing rolls/buns have whole milk.

40% of transactions containing yogurt have whole milk.

21% of transactions containing whole milk have yogurt.

In [39]:
!pip install mlxtend --upgrade

Requirement already satisfied: mlxtend in /usr/local/lib/python3.7/dist-packages (0.14.0)
Collecting mlxtend
  Downloading mlxtend-0.19.0-py2.py3-none-any.whl (1.3 MB)
     |████████████████████████████████| 1.3 MB 7.7 MB/s
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from mlxtend) (57.4.0)
Requirement already satisfied: matplotlib>=3.0.0 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (3.2.2)
Requirement already satisfied: scipy>=1.2.1 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.4.1)
Requirement already satisfied: joblib>=0.13.2 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.1.0)
Requirement already satisfied: scikit-learn>=0.20.3 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.0.1)
Requirement already satisfied: numpy>=1.16.2 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.19.5)
Requirement already satisfied: pandas>=0.24.2 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.1.5)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.0.0->mlxtend) (2.8.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.3.2)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.0.0->mlxtend) (3.0.6)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.0.0->mlxtend) (0.11.0)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.2->mlxtend) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.1->matplotlib>=3.0.0->mlxtend) (1.15.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.20.3->mlxtend) (3.0.0)
Installing collected packages: mlxtend
  Attempting uninstall: mlxtend
    Found existing installation: mlxtend 0.14.0
    Uninstalling mlxtend-0.14.0:
      Successfully uninstalled mlxtend-0.14.0
Successfully installed mlxtend-0.19.0

# Fpgrowth

> Now we are appyling the gpgrowth algorithm with min_support as 0.05. We can see the below results with their min_support >=0.05.

In [16]:
freq_items=fpgrowth(basket_sets, min_support=0.05,use_colnames=True)
freq_items

     support                                  itemsets
0   0.082766                       (item_citrus fruit)
1   0.058566                          (item_margarine)
2   0.139502                             (item_yogurt)
3   0.104931                     (item_tropical fruit)
4   0.058058                             (item_coffee)
5   0.255516                         (item_whole milk)
6   0.075648                          (item_pip fruit)
7   0.193493                   (item_other vegetables)
8   0.055414                             (item_butter)
9   0.183935                         (item_rolls/buns)
10  0.080529                       (item_bottled beer)
11  0.110524                      (item_bottled water)
12  0.053279                               (item_curd)
13  0.052466                               (item_beef)
14  0.174377                               (item_soda)
15  0.058973                        (item_frankfurter)
16  0.079817                         (item_newspapers)
17  0.072293              (item_fruit/vegetable juice)
18  0.088968                             (item_pastry)
19  0.108998                    (item_root vegetables)
20  0.077682                        (item_canned beer)
21  0.093950                            (item_sausage)
22  0.098526                      (item_shopping bags)
23  0.064870                        (item_brown bread)
24  0.052364                            (item_napkins)
25  0.071683                 (item_whipped/sour cream)
26  0.057651                               (item_pork)
27  0.063447                      (item_domestic eggs)
28  0.056024            (item_yogurt, item_whole milk)
29  0.074835  (item_other vegetables, item_whole milk)
30  0.056634        (item_whole milk, item_rolls/buns)

## Association rules

> Here we are printing the association rules with confidence as the metric and min_threshold as 0.1. We can see the results below.

In [19]:
rules = association_rules(freq_items, metric="confidence", min_threshold=0.1)
rules.head(5)

               antecedents              consequents  ...  leverage  conviction
0            (item_yogurt)        (item_whole milk)  ...  0.020379    1.244132
1        (item_whole milk)            (item_yogurt)  ...  0.020379    1.102157
2  (item_other vegetables)        (item_whole milk)  ...  0.025394    1.214013
3        (item_whole milk)  (item_other vegetables)  ...  0.025394    1.140548
4        (item_whole milk)        (item_rolls/buns)  ...  0.009636    1.048452

[5 rows x 9 columns]

## Patterns


40% of transactions containing yogurt have whole milk.

21% of transactions containing whole milk have yogurt.

38% of the transactions containing vegetables contain whole milk.

29% of transactions containing whole milk have vegetables.

22% of transactions containing whole milk have rolls/buns.

# References

http://rasbt.github.io/mlxtend/user_guide/frequent_patterns/apriori/

http://rasbt.github.io/mlxtend/user_guide/frequent_patterns/fpgrowth/